#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Marvio Rocha 

# Short bio or description (displayed in the header)
description: Web Developer from Somewhere


url: 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png




# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Buynow url for payding product
homepage:
  - title: Aprenda partituras em até 30 dias
    image: /images/ebook-medium.png
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate.
    buynow: https://www.mercadopago.com.br/


# sele page button

sele_title: Adquira agora seu exemplar
sele_description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime

seles:
  - price: "19.90"
    title: Por apenas
    subtitle: "Super desconto de: <s>47.90</s> por apenas"
    image: /images/ebook-medium.png
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate.
    buynow: https://www.mercadopago.com.br


# info site midle

info:
  - title: Lorem ipsomi dolorAdipisicing
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 
    icon: heart

  - title: Lorem ipsomi dolorAdipisicing
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 
    icon: music

  - title: Lorem ipsomi dolorAdipisicing
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 
    icon: headphones

# FAQ Session site
  
faq:
  - section: Secion 1
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 

  - section: Secion 2
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 

  - section: Secion 3
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 

  - section: Secion 4
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 

  - section: Secion 5
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus impedit cupiditate. 

# Depoiment session site

depoiment_title: Title the depiment here
depoiment_description:  Lorem ipsum dolor sit amet, consectetur adipisicing 


depoiment:
  - name: Juju
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus 
    city: Campos-RJ
    foto: https://bulma.io/images/placeholders/128x128.png

  - name: Mislene 
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus 
    city: Macaé 
    foto: https://bulma.io/images/placeholders/128x128.png

  - name: Guilherme
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus 
    city: Campos-RJ
    foto: https://bulma.io/images/placeholders/128x128.png

  - name: Diego
    description: lorem ipsom dolorAdipisicing aliquid odio eaque quo maxime Nesciunt necessitatibus 
    city: Macaé
    foto: https://bulma.io/images/placeholders/128x128.png





# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
