backend:
  name: test-repo
  branch: master # Branch to update (optional; defaults to master)
  site_url: https://partituras30dias.showbiz.mus.br/
  display_url: https://partituras30dias.showbiz.mus.br/
media_folder: 'images/uploads'

collections:

# Home Page Settings
- name: "config"
  label: "Site Config"
  editor: 
    preview: false
  files:
    - label: "Geral"
      name: "geral"
      file: "_data/global.yml"
      fields:
        - {lavel: Title, name: title, widget: string}
    - label: "Navigation"
      name: "navigation"
      file: "_data/nav.yml"
      fields:
        - label: "Itens do menu"
          name: "items"
          widget: "list"
          fields:
            - {label: Name, name: title, widget: string}
            - {label: Link, name: url, widget: string}


- name: "home"
  label: "Ebook"
  editor:
    preview: false
  files:
    - label: "Home"
      name: "home"
      file: "_data/home.yml"
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Ebook Imagem", name: "image", widget: "image", default: "/images/ebook-medium.png"}
        - {label: "Descrição", name: "description", widget: "text"}
        - {label: "Button URL", name: "buynow", widget: "string"}
- name: "Faq"
  label: "Faq"
  editor:
    preview: false
  files:
    - label: "FAQ"
      name: "faq"
      file: "_data/faq.yml"
      fields:
        - label: "FAQ"
          name: "Item faq"
          widget: "list"
          fields:
            - {label: Section, name: section, widget: string}
            - {label: Descripion, name: description, widget: text}