backend:
  name: test-repo
  branch: master # Branch to update (optional; defaults to master)
  site_url: https://partituras30dias.showbiz.mus.br/
  display_url: https://partituras30dias.showbiz.mus.br/
media_folder: 'images/uploads'

collections:

# Home Page Settings

- name: "home"
  label: "Inicial"
  editor:
    preview: false
  files:
    - label: "Home"
      name: "home"
      file: "_data/home.yml"
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Ebook Imagem", name: "image", widget: "image", default: "/images/ebook-medium.png"}
        - {label: "Descrição", name: "description", widget: "text"}
        - {label: "Button URL", name: "buynow", widget: "string"}

# Menu navigation 

- name: "nav"
  label: "Menu"
  editor:
    preview: false
  files:
    - label: "Menu"
      name: "navigation"
      file: "_data/nav.yml"
      widget: "list"
      fields:
        - {label: "Menu", name: title, widget: string}
        - {label: "Link", name: url, widget: string}