backend:
  name: test-repo
  
  
media_folder: 'images/uploads'

collections:
- name: "home"
  label: "Inicial"
  files:
    - label: "Home"
      name: "home-page"
      file: "_data/home.yml"
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Ebook Imagem", name: "image", widget: "image", default: "/images/ebook-medium.png"}
        - {label: "Descrição", name: "description", widget: "text"}
        - {label: "Button URL", name: "buynow", widget: "string"}

# menu navigation 

- name: "menu"
  label: "Menu"
  editor:
    preview: false
  files:
    - label: "Menu"
      name: "menu"
      file: "_data/nav.yml"
      fields:
        - {label: "Menu", name: name, widget: string}
        - {label: "link", name: link, widget: string}